. $qlib/dotfiles/zshrc
# Generated by Groq bootstrap; END; DO NOT EDIT.
# conflux-lite telemetry env
[ -z "${CONFLUX_LITE_DISABLE:-}" ] && [ -f "$HOME/.conflux-lite/env.sh" ] && . "$HOME/.conflux-lite/env.sh"
