#!/usr/bin/env zsh

errors=$HOME/.xsession-errors
exec >>$errors 2>&1

# qlib=$HOME/qlib

setxkbmap -option ctrl:nocaps -option terminate:ctrl_alt_bksp
xmodmap $qlib/kbd/dvorak.xmodmap
xmodmap $qlib/dotfiles/xmodmap

xrdb -merge $qlib/Xresources

cd

xset +fp /usr/share/fonts/local
# xset m 6  # mouse accelleration
xset dpms 600 1200 0
xset b off

# bggen black red yellow green cyan blue purple black | xv -root -quit  - &
xsetroot -solid gray30
# xsetroot -cursor ~/gfx/x-cursor ~/gfx/x-cursor-mask

all-xterms

# xload -nolabel -update 3 -hl red -geometry 255x74+0+0 &
xload -nolabel -update 3 -hl red -geometry 640x88+0+0 &

# xsysinfo -update 500 -geometry 212x74+255+0 &
xclock -padding 4 -d -strftime '%I:%M %a %d' -geometry +0+0 &

# nvidia-settings --load-config-only &
# xscreensaver -no-splash &

fvwm2
# next login will clobber .xsession-errors
mv $errors $errors.last
