#!/bin/zsh
cd
dotfiles=(
    .fvwm2rc .inputrc .vim .vimrc .zlogin .zshenv .zshrc .haskeline .ghci
    .editrc
)
for fn in $dotfiles; do
    ln -fs qlib/dotfiles/$fn
done

rm -rf bin
ln -s qlib/bin

ln -sf qlib/sys/$host/xsession .xsession
