#!/bin/zsh -e
qlib=$(realpath $(dirname $(pwd)/$0))

cd
dotfiles=(
    .fvwm2rc .inputrc .vim .zlogin .zshenv .zshrc .haskeline .ghci
    .editrc .gitconfig .darcs .tmux.conf
)
for fn in $dotfiles; do
    ln -Ffs $qlib/dotfiles/$fn
done
mkdir -p .config

# Don't mess up any local configs that may exist.
for fn in $qlib/dotfiles/.config/*(N); do
    ln -Ffs ../$fn .config
done

rm -rf bin
ln -s $qlib/bin

ln -sf $qlib/sys/$host/xsession .xsession
ln -sf .xsession .xinitrc
