alias s='ls -FG'
alias blog='vi ~/n/blog/$(y-m-d)'

alias make='make -j3' # dual core!
alias d=darcs
alias vim=/usr/local/bin/vim

export TEST_R3DB_USER=root
export TEST_R3DB_PASSWD=test
export TEST_R3DB_DBNAME=test_r3

export XLISPPATH=/usr/local/src/nyquist/runtime:/usr/local/src/nyquist/lib

src=/usr/local/src
dl=$HOME/Downloads

function darcs {
    if [[ -e tools/darcs ]]; then
        tools/darcs "$@"
    else
        command darcs "$@"
    fi
}
