# path=($path /home/build/public/google/tools /home/build/public/eng/perforce)
path=($path /usr/local/scripts /usr/local/symlinks)
path=($path /usr/local/stash/src/ghc-6.4/bin/i386-unknown-linux)

path=(~/bin/$host ~/bin ~/bin/$(~/bin/oname) /usr/local/bin $path)

unset GREP_OPTIONS GREP_COLOR # kill google default env

pythonpath=($HOME/lib/python /home/build)

: ${P4CONFIG:=.p4config}
: ${P4DIFF:=/home/build/public/google/tools/p4diff -w}
: ${P4MERGE:=/home/build/public/eng/perforce/mergep4.tcl}
: ${P4EDITOR:=$EDITOR}
export P4CONFIG P4DIFF P4MERGE P4EDITOR
