function mldb {
  mysql -hmdbsqlro -P9200 -A mdb
}

# don't check for silly X, and don't use silly google vimrc
alias vi='vim -X -u $HOME/.vimrc'

alias runtests='tools/make-dbg runtests'

# function g4 {
# 	(cd $(command pwd); command g4 "$@")
# }
