umask 022  # google setup started setting umask of 027

g3=/home/build/google3

export qtraceback_truncate=128 # display lots of arglist context

function mldb {
    mysql -hmdbsqlro -P9200 -A mdb
}

function cdr {
    if [[ $PWD = */google3/* || $PWD = */google3 ]]; then
        if [[ $PWD = */READONLY/* || $PWD = */READONLY ]]; then
            cd READONLY ''
        else
            cd google3 READONLY/google3
        fi
    else
        echo not in google3
        return 1
    fi
}

function cdt {
    if [[ $PWD = */google3/java/* ]]; then
        cd java javatests
    elif [[ $PWD = */google3/javatests/* ]]; then
        cd javatests java
    else
        echo not in google3/java
        return 1
    fi
}

local proxy=http://proxyconfig.corp.google.com/wpad.dat

# don't check for silly X, and don't use silly google vimrc
alias vi='command vim -X -u $HOME/.vimrc'
alias google-chrome="command google-chrome --proxy-pac-url=$proxy"
alias snip='vi ~/n/snip/$(y-m-d)'

alias f=fileutil
alias ft='fileutil --gfs_user=gt-team'

# build with special flags for flume
function fbuild {
    blaze build --nolegacy_java_swigdeps $1_deploy.jar
}

# 'friends' is empty, so disable ~ completion since it's so slow
compctl -T -x 's[~] C[0,[^/]#]' -k friends -S/ -tn


# function g4 {
# 	(cd $(command pwd); command g4 "$@")
# }
