# locally compiled vim 8 with clipboard support
alias vi=/usr/local/bin/vim
alias vi=/opt/homebrew/bin/vim
alias s='ls -FG'
alias blog='vi ~/n/blog/$(y-m-d)'

alias make='make -j6'

src=/usr/local/src
dl=$HOME/Downloads

export LEDGER_FILE=$HOME/src/money/journal/main.j
