alias s='ls -FG'
alias blog='vi ~/n/blog/$(y-m-d)'

alias make='make -j3' # dual core!
alias vim=/usr/local/bin/vim

src=/usr/local/src
dl=$HOME/Downloads
doc=/usr/local/share/doc # haskell docs

# Look in $CWD for a bin directory.
path=(bin $path)

unalias d
function d() {
    if [[ $1 = g ]]; then
        shift
        darcs diff --diff-command 'opendiff %1 %2' "$@"
    else
        darcs "$@"
    fi
}
