alias s='ls -FG'
alias blog='vi ~/n/blog/$(y-m-d)'

alias make='make -j6'

# for phabricator for ghc
alias arc=$src/hs/arcanist/bin/arc

src=/usr/local/src
dl=$HOME/Downloads
doc=/usr/local/share/doc # haskell docs

# Look in $CWD for a bin directory.
path=(bin $path)

unalias d
function d() {
    if [[ $1 = g ]]; then
        shift
        darcs diff --diff-command 'opendiff %1 %2' "$@"
    else
        darcs "$@"
    fi
}
