let maplocalleader = ","

" stop syntax/syncolor.vim from doing anything
let syntax_cmd = "mine"
" :syntax enable will reset syntax_cmd
runtime syntax/syntax.vim

filetype plugin on

au BufNewFile *.hs,*.hsc        so ~/.vim/hs-new.vim
" " GHC profile output.
" au BufRead,BufNewFile *.prof    set shiftwidth=1 | set foldmethod=indent | set foldnestmax=20
au BufRead,BufNewFile */p/*.hs  so ~/.vim/groq.vim

" reset everything to defaults
set all&

set encoding=utf8
set noloadplugins " don't read crap from $VIM/plugins
set nocompatible " no vi compatibility, matchparen requires this
runtime plugin/matchparen.vim " wait, except I like this one

set exrc " read .vimrc from the current directory too
set completeopt=preview " vim started adding an annoying menu by default

" Key mappings timeout after 1 sec, key codes after .1 sec.
set timeoutlen=1000 ttimeoutlen=100

set foldignore=
" Vim is buggy and won't open a fold if a search jumps into it, even if
" 'search' is in foldopen.  'all' will make it open, but is otherwise useless
" because it won't let you close a fold at all.
set foldopen=block,hor,insert,jump,mark,percent,quickfix,search,tag,undo

set ts=8 sw=4 expandtab smarttab
set bs=2 helpheight=99 showcmd ruler gdefault
set showmatch incsearch hlsearch
set nostartofline fileformats=unix,dos,mac

" or full,list
set wildmode=longest,list

" only one indent in parens, but I actually like the 2*
" set cinoptions=(4
" c indent continuation lines are just a single indent + 0 spaces
" set cinoptions=+0

set visualbell t_vb=
set comments=

" wrap text, comments, format comments
set formatoptions=tcroq
" don't break lines already past tw, break and join chinese sensibly
set formatoptions+=lmM

set nolisp
set textwidth=0
set wrap

" eliminate annoying press enter to continue msgs with long paths
set shortmess=atI
set cmdheight=1

set wildmode=longest,list
set wildignore=*.o,*.pyc,*.pyo,*.hi,*.hi-boot,*.o-boot,*.class
set hidden

set notagrelative " don't look for tags relative to the edited file
" files and tab completion are case sensitive, even on OS X
set nofileignorecase

mapclear
mapclear!

" vim is buggy and doesn't open folds even though its set to
" nm <silent> n /<cr>
" nm <silent> N ?<cr>

nmap ,e   :edit 
nmap ;e   :edit <C-R>=expand("%:h") . "/" <CR>
nmap ,o   :buffer 
nmap ;o   :buffer <C-R>=expand("%:h") . "/" <CR>
nmap ,l   :ls<cr>
nmap ,u   :bdelete<cr>

" I never actually want to look up a man page.
nm K k
vm K k

" fix traditional vi annoyances
nmap Y  y$
nmap '' ``
" Get rid of useless control-space behaviour.
imap <Nul> <Space>

nmap <down> <c-e>
nmap <up> <c-y>
nmap <c-@> @@

" complete filenames
inoremap <c-f>   <c-x><c-f>
" complete tags
inoremap <c-]> <c-x><c-]>

nm gqp  gqap
nm gz   :wa<cr>
nm Q gq

" nm <silent> ,s :nohlsearch<cr>:match<cr>
nm <silent> ,s :nohlsearch<cr>
" nm <silent> ,n :exe 'match IncSearch "\<' . expand("<cword>") . '\>"'<cr>
nm <silent> ,n :let @/='<C-R><C-W>'<CR>:set hls<CR>
" nm <Leader>* :let @/='\<'.expand('<cword>').'\>'<CR>

nm ,c V,c

" # is default comment
vm ,c :!cmt '\#'<cr>

" ,d insert current date
nm <silent> ,d  :r !date +\%Y-\%m-\%d<cr>
nm <silent> ,D  :r !date +\%Y-\%m-\%d:\%H:\%M:\%S<cr>

" clear out trailing whitespace and lines ending in whitespace
nm <silent> ,w   :%s/[\t ]\+$//e<cr>

" ,p toggle paste mode
nm ,p   :se invpaste<cr>:se paste?<cr>

nm <c-j> :next<cr>

" trailing spaces are always bad
syntax match ErrorMsg   display "\s\+$"
" mixed tabs and spaces
syntax match ErrorMsg   display " \+\t"
syntax match ErrorMsg   display "\t\+ "

" mark columns 80 and 81 in red for long lines...
match ErrorMsg /\%80v.\%81v./

set cpoptions= " turn off more vi compatibility

if v:progname == 'nvim'
    set cpoptions=_ " restore normal cw, neovim breaks this
endif

if has('python')
    py import sys, os, vim
    py sys.path.insert(0, os.environ['HOME'] + '/.vim/py')
    py import swapwords

    nm <silent> <c-s> :py swapwords.vim_swap_word(vim)<cr>
    nm <silent> <c-n> :py swapwords.vim_swap_delim(vim)<cr>
elseif has('python3')
    py3 import sys, os, vim
    py3 sys.path.insert(0, os.environ['HOME'] + '/.vim/py')
    py3 import swapwords

    nm <silent> <c-s> :py3 swapwords.vim_swap_word(vim)<cr>
    nm <silent> <c-n> :py3 swapwords.vim_swap_delim(vim)<cr>
endif

" source ~/.vim/bundle/vim-surround/plugin/surround.vim
" set runtimepath^=~/.vim/bundle/vim-surround
" set runtimepath^=~/.vim/bundle/ctrlp.vim

" Disable for now.
" let g:loaded_ctrlp = 1

" let g:ctrlp_map = '<c-p>'
" let g:ctrlp_switch_buffer = 'Et'
" let g:ctrlp_custom_ignore = '\v(_darcs|\.git)$'
" runtime plugin/ctrlp.vim
