let maplocalleader = ","
let mapleader = ","

" stop syntax/syncolor.vim from doing anything
let syntax_cmd = "mine"
" let syntax_manual = "true"

" :syntax enable will reset syntax_cmd
runtime syntax/syntax.vim

filetype plugin on

au BufNewFile *.hs,*.hsc        so ~/.vim/hs-new.vim
" " GHC profile output.
" au BufRead,BufNewFile *.prof    set shiftwidth=1 | set foldmethod=indent | set foldnestmax=20
au BufRead,BufNewFile */p/*.hs  so ~/.vim/groq.vim

" reset everything to defaults
set all&

set encoding=utf8
set noloadplugins " don't read crap from $VIM/plugins
set nocompatible " no vi compatibility, matchparen requires this
runtime plugin/matchparen.vim " wait, except I like this one

set exrc " read .vimrc from the current directory too
set completeopt=preview " vim started adding an annoying menu by default

" Key mappings timeout after 1 sec, key codes after .1 sec.
set timeoutlen=1000 ttimeoutlen=100

set foldignore=
" Vim is buggy and won't open a fold if a search jumps into it, even if
" 'search' is in foldopen.  'all' will make it open, but is otherwise useless
" because it won't let you close a fold at all.
set foldopen=block,hor,insert,jump,mark,percent,quickfix,search,tag,undo

set ts=8 sw=4 expandtab smarttab
set bs=2 helpheight=99 showcmd ruler gdefault
set showmatch incsearch hlsearch
set nostartofline fileformats=unix,dos,mac

" or full,list
set wildmode=longest,list

" only one indent in parens, but I actually like the 2*
" set cinoptions=(4
" c indent continuation lines are just a single indent + 0 spaces
" set cinoptions=+0

set visualbell t_vb=
set comments=:#

" wrap text, comments, format comments
set formatoptions=tcroq
" delete commments on J
set formatoptions+=j
" don't break lines already past tw, break and join chinese sensibly
set formatoptions+=lmM

set nolisp
set textwidth=0
set wrap

" eliminate annoying press enter to continue msgs with long paths
set shortmess=atI
set cmdheight=1

set wildmode=longest,list
set wildignore=*.o,*.pyc,*.pyo,*.hi,*.hi-boot,*.o-boot,*.class
set hidden

set notagrelative " don't look for tags relative to the edited file
" files and tab completion are case sensitive, even on OS X
set nofileignorecase

" Read changed files without prompting.  This happens a lot due to git
" checkout, and vim only uses mtime so it's wrong a much of the time.
set autoread

mapclear
mapclear!

" vim is buggy and doesn't open folds even though its set to
" nmap <silent> n /<cr>
" nmap <silent> N ?<cr>

nmap ,e   :edit 
nmap ;e   :edit <C-R>=expand("%:h") . "/" <CR>
nmap ,o   :buffer 
nmap ;o   :buffer <C-R>=expand("%:h") . "/" <CR>
nmap ,l   :ls<cr>
nmap ,u   :bdelete<cr>

" grep
nnoremap ,g :call Rg('\\b' . expand('<cword>') . '\\b')<cr>
fun! Rg(txt)
    if &filetype == ''
        let &grepprg = 'rg --vimgrep'
    elseif &filetype == 'c'
        let &grepprg = 'rg --vimgrep --type=c --type=cpp'
    else
        let &grepprg = 'rg --vimgrep --type=' . &filetype
    endif
    silent! exe 'grep! ' . a:txt
    if len(getqflist()) > 0
        copen
        redraw!
    else
        cclose
        redraw!
        echo 'no match: ' . a:txt
    endif
endfun
command! -nargs=* -complete=tag Rg :call Rg(<q-args>)

" I never actually want to look up a man page.
nmap K k
vmap K k

" fix traditional vi annoyances
nmap Y  y$
nmap '' ``
" Get rid of useless control-space behaviour.
imap <Nul> <Space>

nmap <down> <c-e>
nmap <up> <c-y>
nmap <c-@> @@

" complete filenames
inoremap <c-f>   <c-x><c-f>
" complete tags
inoremap <c-]> <c-x><c-]>

nmap gqp  gqap
nmap gz   :wa<cr>
nmap Q gq

" nmap <silent> ,s :nohlsearch<cr>:match<cr>
nmap <silent> ,s :nohlsearch<cr>
" nmap <silent> ,h :exe 'match IncSearch "\<' . expand("<cword>") . '\>"'<cr>
nmap <silent> ,h :let @/='<C-R><C-W>'<CR>:set hls<CR>
" nmap <Leader>* :let @/='\<'.expand('<cword>').'\>'<CR>

nmap ,c V,c

" # is default comment
vmap ,c :!cmt '\#'<cr>

" ,d insert current date
nmap <silent> ,d  :r !date +\%Y-\%m-\%d<cr>
nmap <silent> ,D  :r !date +\%Y-\%m-\%d:\%H:\%M:\%S<cr>

" clear out trailing whitespace and lines ending in whitespace
nmap <silent> ,w   :%s/[\t ]\+$//e<cr>

" ,p toggle paste mode
nmap ,p   :se invpaste<cr>:se paste?<cr>

nmap <c-j> :next<cr>

" mark columns 80 and 81 in red for long lines...
match ErrorMsg /\%80v.\%81v./

set cpoptions= " turn off more vi compatibility

if v:progname == 'nvim'
    set cpoptions=_ " restore normal cw, neovim breaks this
endif

if has('python')
    py import sys, os, vim
    py sys.path.insert(0, os.environ['HOME'] + '/.vim/py')
    py import swapwords

    nmap <silent> <c-s> :py swapwords.vim_swap_word(vim)<cr>
    nmap <silent> <c-n> :py swapwords.vim_swap_delim(vim)<cr>
elseif has('python3')
    py3 import sys, os, vim
    py3 sys.path.insert(0, os.environ['HOME'] + '/.vim/py')
    py3 import swapwords

    nmap <silent> <c-s> :py3 swapwords.vim_swap_word(vim)<cr>
    nmap <silent> <c-n> :py3 swapwords.vim_swap_delim(vim)<cr>
endif

" source ~/.vim/bundle/vim-surround/plugin/surround.vim
" set runtimepath^=~/.vim/bundle/vim-surround
" set runtimepath^=~/.vim/bundle/ctrlp.vim

" Disable for now.
" let g:loaded_ctrlp = 1

" let g:ctrlp_map = '<c-p>'
" let g:ctrlp_switch_buffer = 'Et'
" let g:ctrlp_custom_ignore = '\v(_darcs|\.git)$'
" runtime plugin/ctrlp.vim
