#!/bin/sh

qlib=$HOME/qlib

# re-enable x zap in new xorg versions
setxkbmap -option terminate:ctrl_alt_bksp

xmodmap $qlib/kbd/dvorak.xmodmap
xmodmap $qlib/dotfiles/xmodmap

if cd $qlib/Xresources; then
	for f in *; do xrdb -quiet $f; done
fi
xrdb -merge $qlib/dotfiles/Xresources

cd

# xset m 6  # mouse accelleration
xset dpms 600 1200 0
xset b off

# bggen black red yellow green cyan blue purple black | xv -root -quit  - &
xsetroot -solid gray30
# xsetroot -cursor ~/gfx/x-cursor ~/gfx/x-cursor-mask

xload -nolabel -update 3 -hl red -geometry 255x74+0+0 &
xsysinfo -update 1000 -geometry 308x74+257+0 &
xclock -padding 4 -d -strftime '%I:%M %a %d' -geometry +0+0 &

# nvidia-settings --load-config-only &

xscreensaver -no-splash &

xterm&
# xmonad
fvwm2
# next login will clobber .xsession-errors
mv ~/.xsession-errors ~/.xsession-errors.last
