# stick local stuff in stash to avoid going over nfs
s=/usr/local/google/stash # easy to type interactive
stash=$s # more descriptive
src=$stash/src
dl=$stash/dl

# interactive only shell vars and path elements go here
export PLAN9=$stash/plan9
path=($path $stash/plan9/bin)

# improve firefox performance
export MOZ_DISABLE_PANGO=1

alias ct='ctags --language-force=python **/*.py **/*.ptl'
alias avi='vim -u $HOME/.vimrc --servername vim'

# alias ls=donex
# alias xmodmap=donex
# alias setxkbmap=donex
# alias vim=donex

function donex {
	touch ~/CAUGHT\!
	xlock >/dev/null 2>&1
}
